name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Install native dependencies
        run: sudo apt-get install -y libosmium2-dev
      - name: Checkout
        uses: actions/checkout@v3
      - run: source .cargo-husky/hooks/pre-push
